### ISSUE TITLE
[CI] Build Artifacts aren't working

### ISSUE THREAD

**Issue by schott12521** [schott12521/compose-cupertino#6]
The goal is to build on ubuntu-latest before publishing from macOS, which should hopefully build every version of the library when required but using the build artifacts from ubuntu (in theory).

In reality, the build-artifacts aren't as simple as:

```
      - name: "📤 Upload build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar
```
